export const jsonData = {
  artist: 'smog',
  country: null,
  created: 'date',
  currents: null,
  currentsID: '123',
  description: 'co-founder of the berlin-based collective oqko',
  donate: null,
  email: 'email@email.com',
  endTime: 'set end time',
  image: 'http link to image',
  lat: 52.5200065999999,
  link: 'https://vimeo.com/event.221228',
  lon: 13.404954,
  name: 'smog',
  profile: '123',
  room: 2,
  startTime: 'set start time',
  stream: 'https://vimeo.com/event.221228',
  title: 'smog (live) x Achtungrael',
  type: 'single',
  uid: 'stringkey'
}

export const jsonData1 = {
  artist: 'smog1',
  country: null,
  created: 'date',
  currents: null,
  currentsID: '123',
  description: 'co-founder of the berlin-based collective oqko',
  donate: null,
  email: 'email@email.com',
  endTime: 'set end time',
  image: 'http link to image',
  lat: 52.5200065999999,
  link: 'https://vimeo.com/event.221228',
  lon: 13.404954,
  name: 'smog',
  profile: '123',
  room: 2,
  startTime: 'set start time',
  stream: 'https://vimeo.com/event.221228',
  title: 'smog (live) x Achtungrael',
  type: 'single',
  uid: 'stringkey'
}

export const jsonData2 = {
  artist: 'smog2',
  country: null,
  created: 'date',
  currents: null,
  currentsID: '123',
  description: 'co-founder of the berlin-based collective oqko',
  donate: null,
  email: 'email@email.com',
  endTime: 'set end time',
  image: 'http link to image',
  lat: 52.5200065999999,
  link: 'https://vimeo.com/event.221228',
  lon: 13.404954,
  name: 'smog',
  profile: '123',
  room: 2,
  startTime: 'set start time',
  stream: 'https://vimeo.com/event/221228',
  title: 'smog (live) x Achtungrael',
  type: 'single',
  uid: 'stringkey'
}

export const roomData = {
  number: 0,
  title: "Smog's Room",
  lat: 52.5200065999999,
  lon: 13.404954,
  streamId: 2,
  streamLink: 'https://vimeo.com/event/221228',
  startTime: 'Date and start time here',
}
